### ISSUE TITLE
Voting 

### ISSUE THREAD

**Issue by willcode4tacos** [angela-andrews/upenn-project1#8]
Voting on ballot of nominations requires:
-a counter associated with the unique ID of the user (generated at page load and stored in database under 'users')

-user clicks on nomination (which have .nomination class with attendant event listener), and this adds the nomination to a 'voting' (? or similarly named subnode) subnode in firebase, which also has "score" counter that is updated.

        -logic will be required that looks at the database at the beginning of the click function, 
          and checks to see if the nomination is already in the subnode.  If not, then it push 
          method adds the object (nomination and score).  If exists, set method updates the score
          (sth. like database.ref('votes').set({ score: score+3})

-based on the individual counter, the first vote adds three points to the nominations score, the second, 2, and the third, 1.

**Comment by CatLibWilk** [comment]
Finally got the code working so that it creates a nomination in the voting section when first suggested, and updates the score if its already in the voting section.  I simplified the scoring process by making a voteCount starting at 3 that goes down by one when a restaurant is nominated or voted for.  After the initial entry into the votes section of the database, the score is updated by just taking the score + the current vote count.

**Comment by CatLibWilk** [comment]
What we still need for this is:
-determination that all the votes are in, which then triggers a...

-function that sees which restaurant had the most votes.  Probably make an array of the voted-ons with their ID and score, order the array by highest score, and see which Id is associated with the highest score (I guess, there's I imagine a much easier method to do this)
